import Image from 'next/image';
import { Inter } from 'next/font/google';

import './globals.css';
import StoreProvider from './StoreProvider';

import classicLogo from '../assets/classic-closet-logo.png';
import cartIcon from '../assets/cart_ico.svg';
import searchIcon from '../assets/search_ico.svg';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative">
          <nav className="w-full max-h-24 shadow-xl z-10 px-6 flex justify-between items-center uppercase text-sm bg-white text-red-600 font-bold sticky top-0 right-0">
            <div className="w-36 hover:cursor-pointer">
              <Image
                src={classicLogo}
                className="w-full"
                alt="classic closet logo"
                priority={true}
              />
            </div>
            <ul className="nav-list gap-8 hidden md:flex">
              <li>Home</li>
              <li>About Us</li>
              <li>Contact Us</li>
            </ul>
            <ul className="flex gap-4">
              <li className="flex gap-2 items-center font-medium">
                <Image
                  src={searchIcon}
                  alt="search icon"
                  height={36}
                  width={36}
                />
                Search
              </li>
              <li className="flex gap-2 items-center font-medium">
                <Image src={cartIcon} alt="cart icon" height={36} width={36} />
                Cart
              </li>
            </ul>
          </nav>
          <StoreProvider>{children}</StoreProvider>
        </div>
      </body>
    </html>
  );
}
